default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  database: textacular_dev

production:
  <<: *default
  database: textacular_prod

test:
  <<: *default
  database: textacular_test
